### ISSUE TITLE
Releases with different artists are ripped to individual folders

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#1]
If you rip a release that has different artists for each track, each track will be ripped to its own folder. The proper thing to do would be to rip all the tracks to the same folder, and possibly have the artist set as "Various Artists" or "VA" or something similar.

Example release would be https://listen.tidal.com/album/38610083

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/4e089e9e6142ec84d3b7015b29c6412135fd04d0
