### ISSUE TITLE
[Feature] If something 404's, continue working through the list provided

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#10]
Currently, if you provide multiple albums to rip and one isn't available, you'll get a 404 error. If this happens, the script should just skip that item and continue on. For example, if I provide this list: https://listen.tidal.com/album/3809614 https://listen.tidal.com/album/44402187 https://lis
ten.tidal.com/album/11622501, it will crap out on the second item, and not continue to the third. It would be nice if the script just says "Error: Album not available" or something and just continues on.

This is what happens when it hits the unavailable album currently:
`Traceback (most recent call last):               
  File "/home/aoichan/RedSea/redsea.py", line 117, in <module>
    main()                         
  File "/home/aoichan/RedSea/redsea.py", line 98, in main
    media_info = api.get_album(id)                     
  File "/home/aoichan/RedSea/tidal_api.py", line 56, in get_album
    return self._get('albums/' + str(album_id))  
  File "/home/aoichan/RedSea/tidal_api.py", line 24, in _get                                                     
    raise TidalError(resp)                               
tidal_api.TidalError: 2001: Album [44402187] not found (HTTP 404)
`

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/292874839bda0b4229b6592ba0b7158fda0b315a
