### ISSUE TITLE
[Bug] Issue with rs_config.txt

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#11]
The default rs_config.txt in the repo is broken. I don't know how to send things in, but https://github.com/mreweilk/RedSea/blob/master/rs_config.txt#L9 needs to have its comma removed. Otherwise it's incorrect.

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/eb61632efcc001f1c7ae300670cd70fad09f7678
