### ISSUE TITLE
Some characters are being converted to hyphens in filenames.

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#2]
If you rip something with an & or ' in the track name, the resulting filename will convert the character to a hyphen.

As an example, if you rip this release: https://listen.tidal.com/album/66330194
The resulting filename for track 2 will be "2 New Flows (Rugged - Raw Remix).flac" rather than "2 New Flows (Rugged & Raw Remix).flac"

As well, if you rip this release: https://listen.tidal.com/album/74277668
The resulting track name for Track 2 and Track 3 will be "2 Don-t Mind.flac" and "3 Say You-ll Work It.flac" instead of "2 Don't Mind.flac" and "3 Say You'll Work It.flac"

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/4bc52094fafbdc60d1e48ea15efdccb6d87cf4ac
