### ISSUE TITLE
[Feature Request] Zero pad track numbers in filenames

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#3]
When you rip something, the filenames of the tracks will be "1 - Track Name.flac", "2 - Track Name.flac", etc. It would be much nicer if the track numbers could be zero padded for tracks 1-9, i.e "01 - Track Name.flac", "02 - Track Name.flac", etc. The zero-padding **should not** apply to tracks 10+, as that would mess up sorting.

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/cc756d53ab640acb6868a5f9ee5edb08f0fa12c8
