### ISSUE TITLE
Some characters still not being interpreted correctly

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#4]
As of the latest version, some characters aren't being handled correctly.

If there are multiple artists, they are separated by commas. Currently those multiple artists will be output to a folder name as "Artist1- Artist2", instead of "Artist 1, Artist 2". Example release: https://listen.tidal.com/album/75306354

If there is an exclamation point in an artist name or song, the foldername will appear as "Artist-" instead of "Artist!". I believe the same thing happens for file names. Example: https://listen.tidal.com/album/61677069

If there is a remix of a song along with a featured artist in the track name, the "Remix" portion at the end of the song title will be listed as "-Remix Name-" in the filename, as opposed to "[Remix Name]" as it should be. Example: https://listen.tidal.com/album/72646156

If there is a colon in the album title and the corresponding folder, it should be output as " - " instead of the colon, due to compatibility issues on some systems. So if the album title is "AlbumTitle: Album2", the script currently outputs as "AlbumTitle- Album2". It should output as "AlbumTitle - Album2". The tagging for this should remain unaffected. Example release: https://listen.tidal.com/album/75439232

There are probably a couple other characters that cause this but this is what comes to mind offhand.

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/e686afca21e28723ca7dbf4dcb80da085a7d9c9e
