### ISSUE TITLE
[Feature] Separate Multi-Disc Rips Into Individual Disc Folders

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#6]
For Multi-Disc uploads, the way they are ripped right now is that all the tracks are dumped in to the release folder. For Multi-Disc releases only, a Disc 1/Disc 2/etc folder should be made and the tracks from each disc should be put in their corresponding folders.

For example, on https://listen.tidal.com/album/33746982, instead of being output like this:
03 - God (Interlude).flac
03 - Unhappy.flac
04 - Bowtie (feat. Sleepy Brown and Jazze Pha).flac
04 - Happy Valentine's Day.flac
05 - Spread.flac
05 - The Way You Move (Radio Mix) (feat. Sleepy Brown).flac
06 - The Rooster.flac
...

they would be put in their respective folders like this:
CD1/01 - Intro.flac
CD1/02 - GhettoMusick (Radio Mix).flac
CD1/03 - Unhappy.flac
CD1/04 - Bowtie (feat. Sleepy Brown and Jazze Pha).flac
...
CD2/01 - The Love Below (Intro).flac
CD2/02 - Love Hater.flac
CD3/03 - God (Interlude).flac.
and so on.

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/93242264e72d498d2b6e20d435fca000b258f75f
