### ISSUE TITLE
[Feature] Skip releases/songs when not available in the requested format

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#7]
It would be nice to either have a flag on the command, or an option in the config to skip the downloads of things not available in their requested format. For certain things in Tidal's library, only High/Normal are available and not Lossless, so it'd be nice to skip those things that are high/normal only. Essentially something like the ability to do "redsea --lossless-only https://linkshere".

Below is an example output of something requested in Lossless but there's only High available:
<<< Downloading album: 13 track(s) in total >>>
=== Downloading track ID 11398250 ===
        Track: 01
        Title: Opposite Man
        Artist: True Margrit
        Album: The Juggler's Progress
        ----
        Grabbing stream URL...
        WARNING: LOSSLESS quality requested, but only HIGH quality available.
^C      Download progress: 12%

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/3643e62fb53fe5fc6eb3501b55f424b4e0aa6669
