### ISSUE TITLE
[Feature] Add support for store links

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#9]
You can browse tidal and get the links for albums using store links. Currently store links are not processed properly by the script. If you try grabbing a store version, you'll get this result:
`redsea http://tidal.com/be/store/album/67107661

 /$$$$$$$                  /$$  /$$$$$$
| $$__  $$                | $$ /$$__  $$
| $$  \ $$  /$$$$$$   /$$$$$$$| $$  \__/  /$$$$$$   /$$$$$$
| $$$$$$$/ /$$__  $$ /$$__  $$|  $$$$$$  /$$__  $$ |____  $$
| $$__  $$| $$$$$$$$| $$  | $$ \____  $$| $$$$$$$$  /$$$$$$$
| $$  \ $$| $$_____/| $$  | $$ /$$  \ $$| $$_____/ /$$__  $$
| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$/|  $$$$$$$|  $$$$$$$
|__/  |__/ \_______/ \_______/ \______/  \_______/ \_______/

                    (c) 2016 Joe Thatcher
               https://github.com/svbnet/RedSea

Unknown media type - be
> Download queue: 1/1 items complete (100% done) <

> All downloads completed. <`

Or this:
`redsea http://tidal.com/store/album/67448126

 /$$$$$$$                  /$$  /$$$$$$
| $$__  $$                | $$ /$$__  $$
| $$  \ $$  /$$$$$$   /$$$$$$$| $$  \__/  /$$$$$$   /$$$$$$
| $$$$$$$/ /$$__  $$ /$$__  $$|  $$$$$$  /$$__  $$ |____  $$
| $$__  $$| $$$$$$$$| $$  | $$ \____  $$| $$$$$$$$  /$$$$$$$
| $$  \ $$| $$_____/| $$  | $$ /$$  \ $$| $$_____/ /$$__  $$
| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$/|  $$$$$$$|  $$$$$$$
|__/  |__/ \_______/ \_______/ \______/  \_______/ \_______/

                    (c) 2016 Joe Thatcher
               https://github.com/svbnet/RedSea

Unknown media type - store
> Download queue: 1/1 items complete (100% done) <

> All downloads completed. <`

However, if you remove the /store/ or /cc/store/, it is the exact same link as if it was a direct album link. It would be nice if redsea supported this to rip.

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/eae7f43828032494177e25501917cf72ff9fcae9
